# Generated by Django 3.2.12 on 2023-04-13 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0004_auto_20230413_0108'),
    ]

    operations = [
    ]
